- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -sSL https://download.sourceclear.com/ci.sh | DEBUG=1 bash 
      
     WorkingDirectory:  '$(system.DefaultWorkingDirectory)'
